
# run with:
#
# mkosi --workspace-directory=/scratch/tortone/mkosi-workspace --directory=~/obmc-pkg/deploy/sysroot
#
# destination sysroot directory: ~/obmc-pkg/deploy/sysroot/image

[Distribution]
Distribution=alma
Release=10
Architecture=arm64
RepositoryKeyFetch=yes

[Output]
Format=directory
OutputDirectory=~/sysroot

[Content]
Packages=
        @core
        sudo
        openssh-server
        vim-minimal
        dnf
        chrony
        glibc-langpack-en
RootPassword=pippo123
Hostname=alma-aarch64
Locale=en_US.UTF-8
Timezone=Europe/Rome

